import { User } from "@/types/usuarios/user-types";
import type { MeterStatus } from "@prisma/client";

export const sampleUsers: User[] = [
  {
    id: "usr_001",
    firstName: "Juan",
    lastName: "Pérez",
    username: "Juan Pérez",
    role: "Administrador",
    status: "ACTIVE",
    email: "juan.perez@example.com",
    createdAt: new Date("2023-05-15T10:30:00"),
    meter: {
      id: "mtr_001",
      status: "active" as MeterStatus,
    },
  },
  {
    id: "usr_002",
    firstName: "María",
    lastName: "González",
    username: "María González",
    role: "Usuario",
    status: "ACTIVE",
    email: "maria.gonzalez@example.com",
    createdAt: new Date("2023-07-22T14:45:00"),
    meter: {
      id: "mtr_002",
      status: "inactive" as MeterStatus,
    },
  },
  {
    id: "usr_003",
    firstName: "Carlos",
    lastName: "Rodríguez",
    username: "Carlos Rodríguez",
    role: "Técnico",
    status: "ACTIVE",
    email: "carlos.rodriguez@example.com",
    createdAt: new Date("2023-09-10T09:15:00"),
    meter: {
      id: "mtr_003",
      status: "warning" as MeterStatus,
    },
  },
  {
    id: "usr_004",
    firstName: "Ana",
    lastName: "Martínez",
    username: "Ana Martínez",
    role: "Supervisor",
    status: "ACTIVE",
    email: "ana.martinez@example.com",
    createdAt: new Date("2023-11-05T16:20:00"),
    meter: {
      id: "mtr_004",
      status: "error" as MeterStatus,
    },
  },
  {
    id: "usr_005",
    firstName: "Luis",
    lastName: "Sánchez",
    username: "Luis Sánchez",
    role: "Administrador",
    status: "INACTIVE",
    email: "luis.sanchez@example.com",
    createdAt: new Date("2024-01-18T11:10:00"),
    meter: {
      id: "mtr_005",
      status: "active" as MeterStatus,
    },
  },
  {
    id: "usr_006",
    firstName: "Elena",
    lastName: "López",
    username: "Elena López",
    status: "INACTIVE",
    role: "Usuario",
    email: "elena.lopez@example.com",
    createdAt: new Date("2024-02-27T13:40:00"),
    meter: {
      id: "mtr_006",
      status: "warning" as MeterStatus,
    },
  },
  {
    id: "usr_007",
    firstName: "Miguel",
    lastName: "Fernández",
    username: "Miguel Fernández",
    status: "INACTIVE",
    role: "Técnico",
    email: "miguel.fernandez@example.com",
    createdAt: new Date("2024-03-15T08:50:00"),
    meter: {
      id: "mtr_007",
      status: "inactive" as MeterStatus,
    },
  },
];
